name: "zustandssumme"
description: " "

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jekyll-toc
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

scholar:
  cite_class: citation
  style: frontiers-in-physics
  bibtex_filters:
    - latex
  bibliography_template: bib
